[tool.poetry]
name = "claude-api"
version = "0.1.0"
description = "Building Claude with API"
authors = ["Rahul <iamrahulus@gmail.com>"]
license = "Open Source"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
python-dotenv = "^1.2.2"
anthropic = "^0.116.0"
requests = "^2.34.2"


[tool.poetry.group.dev.dependencies]
ipykernel = "^7.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
